Fix-BW-Weapons
gruppe-adler/grad-factions pull request #18
Opened 2017-11-08 16:36 UTC by AdlerSalbei

2017-11-08 16:41 UTC, Fusselwurm requested changes
:+1: , aber jetzt hat der LAT in der `BwTrop`-faction einen Flecktarnrucksack statt des Tropentarns… dh da müßt noch die Tropentarnentsprechung rein

2017-11-08 16:44 UTC, AdlerSalbei commented
Fixed

2017-11-08 16:45 UTC, Fusselwurm submitted a review, later dismissed

2017-11-09 05:49 UTC, McDiod requested changes
Also *wenn* wir dem `soldier_ar_f` jetzt n 7.62 geben und dafür den `soldier_lite_f` als SAW einführen, zieht das mehrere Sachen nach sich:

* der `Heavy_Gunner_F` und sein Assistent, die vorher das 7.62 hatten, müssten jetzt n Rucksack-HMG bekommen
* der Ammo Bearer müsste als "Assistent" für den `soldier_lite_f`eingeführt werden
* Überarbeiten aller anderen Factions nach dem gleichen Schema
* Anpassen der Readme
* Anpassen der vorplatzierten Einheiten im CO_Template

2017-11-14 19:02 UTC, McDiod commented
Achtung, Readme im master geändert. Einmal updaten, bevor du da in diesem Branch was dran änderst.

2017-11-15 09:55 UTC, Fusselwurm commented
uh, ich würd mir wünschen die Klassennamen für die MG-Schützen nicht zu vermurksen.
Laut https://community.bistudio.com/wiki/Arma_3_CfgVehicles_WEST :

| class name       | description  |
| ---------------- | ------------ |
| B_soldier_AR_F   | Autorifleman |
| B_support_MG_F   | Gunner (HMG) |
| B_Soldier_lite_F | Rifleman (Light) |
| B_HeavyGunner_F | Heavy Gunner |

… dh, der LMG-Schütze / SAW-Schütze des Infanterietrupps ist `Soldier_AR_F`, der HMG-Schütze der an das Stand-MG kommt ist `Support_MG_F`, und `B_HeavyGunner_F` kriegt das großkalibrige aber noch tragbare MG.

`Soldier_Lite_F` ist nur ein Rifleman der nicht so viel tragen will ;)

2017-11-20 12:44 UTC, Fusselwurm commented
see #20

2017-12-03 17:15 UTC, closed without merging